CREATE TABLE orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    shopid VARCHAR(50) NOT NULL,
    uid VARCHAR(255) NOT NULL,
    yuan VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
