CREATE TABLE shop (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    zyid VARCHAR(50) NULL,
    link VARCHAR(255) NOT NULL,
    rdplink VARCHAR(255) NOT NULL,

    pid VARCHAR(255) NOT NULL,
    yuan VARCHAR(255) NULL,
    hide INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
